name: sync_isolate
version: 0.0.1
description: A simple command-line application created by dcli
environment:
  sdk: '>=3.2.0 <4.0.0'

publish_to: none

dependencies:
  dcli: 4.0.5
  file: ^7.0.0
  glob: ^2.1.2
  native_synchronization: 0.2.0
  path: ^1.9.0
  stack_trace: ^1.11.1
  uuid: ^4.4.2

dev_dependencies:
  lint_hard: ^4.0.0
  test: ^1.25.8
